### ISSUE TITLE
Timeout Greater than 20000 ms

### ISSUE THREAD

**Issue by vindicory** [cyrusbuilt/SAMCrashMonitor#3]
Hi, would like to be able to set timeout greater than 20000 ms, to 5 minutes (300000) is this possible?

**Comment by cyrusbuilt** [comment]
Out of curiosity... why would you want to?  I'm not trying to sound condescending, but that is a super long timeout value for a watchdog. Typically, if your firmware hangs for more than a few seconds, you have a problem.  The exception would be the occasional network operation that is taking too long. But to safeguard against a hang, you would typically use some kind of a timeout and either abort before then end of the timeout and try again, or just give up.

The AVR-series chips have a max timeout value of 8 seconds.  On the ESPs, it doesn't matter what you set the software watchdog to because if an operation takes longer than 4 seconds the hardware watchdog will automatically reset the MCU regardless of what the software watchdog is set to (which is about 2 seconds by default).

On any chip and in any scenario, you have to "feed" the watchdog BEFORE the timeout period or the watchdog triggers when the timeout interval expires. With this library that means you MUST call iAmAlive() at regular intervals (at least once before the end of the timeout) or the chip resets.

My recommendation would be: whatever is you are doing, you should be calling iAmAlive() while you wait if you really need some long-running operation to keep running.  Could you give me some use-case example where you would need such a lengthy timeout?

Looking at the SAM D21 datasheet, I don't see a way to achieve a 5 minute timeout, let alone anything beyond 20s (which is already the longest watchdog timeout I've ever seen).
